### PR TITLE
Add LR(1) Item definitions

### PR DESCRIPTION
**Pull request by SaurusXI**
LR(1) items will be used to make a CLR(1) parsing table, which is the next goal on the roadmap. The CLR(1) parsing table will be used in the parser.

### CODE REVIEW

**Comment by SaurusXI** [comment]
@Geek-ubaid although progress since last PR is not that substantial, I have a feeling I'll be making many commits so I'm making PRs periodically, so that they can be reviewed more easily

**Comment by SaurusXI** [comment]
@Geek-ubaid please review this batch of commits, there's many more coming :)

**Comment by SaurusXI** [comment]
@Geek-ubaid have implemented a `Grammar` module that takes a grammar specification file as an input and parses it to extract all possible grammar productions from it. The plan is to use this module to generate a grammar instance, then implement first, follow, closure, and goto functions on the grammar in the `parse_tree` module, and use them on the grammar instance to generate a parsing table. The parsing table would then allow us to create a parse tree.

**Comment by SaurusXI** [comment]
The `Grammar` module does need to be tested for bugs though.

**Review by Geek-ubaid — APPROVED** [review]

**Pull request merged**
